Name: "prometheus"
ChartName: "tools/kube-prometheus-stack"
Category: "Observability"
Description: "Intelops Grafana"
RepoName: "tools"
RepoURL: "https://kube-tarian.github.io/helmrepo-supporting-tools"
Namespace: "observability"
ReleaseName: "prometheus"
Version: "1.0.7"
CreateNamespace: true
PrivilegedNamespace: true
LaunchURL: https://grafana.{{.DomainName}}/login/generic_oauth
LaunchUIDescription: "Intelops Grafana"
LaunchUIIcon: "grafana.svg"
LaunchUIValues:
  grafana:
    grafana.ini:
      auth.generic_oauth:
        enabled: true
        name: Intelops
        allow_sign_up: true
        client_id: "{{.ClientId}}"
        client_secret: "{{.ClientSecret}}"
        scopes: "openid email"
        auth_url: "{{.OAuthBaseURL}}/oauth2/auth"
        token_url: "{{.OAuthBaseURL}}/oauth2/token"
        api_url: "{{.OAuthBaseURL}}/userinfo"
        allow_assign_grafana_admin: true
      server:
        root_url: https://grafana.{{.DomainName}}/
OverrideValues:
  DomainName: "{{.DomainName}}"
