Name: "traefik"
ChartName: "tools/traefik"
Category: "Networking"
Description: ""
RepoName: "tools"
RepoURL: "https://kube-tarian.github.io/helmrepo-supporting-tools"
Namespace: "traefik"
ReleaseName: "traefik"
Version: "1.0.3"
CreateNamespace: true
