region: "centralindia"
mastercount: 3
workercount: 3
nics: [ "talos-nic-master1" , "talos-nic-master2", "talos-nic-master3", "talos-nic-worker1", "talos-nic-worker2", "talos-nic-worker3"] 
instancetype: "Standard_DS1_v2"
publicipname: "talos-public-ip"