region: "centralindia"
mastercount:
  - "talos-master1"
  - "talos-master2"
  - "talos-master3"
workercount:
  - "talos-worker1"
  - "talos-worker2"
  - "talos-worker3"
nics:
  - "talos-nic-master1"
  - "talos-nic-master2" 
  - "talos-nic-master3"
workernics:
  - "talos-nic-worker1"
  - "talos-nic-worker2"
  - "talos-nic-worker3"

instancetype: "Standard_DS1_v2"
publicipname:
  - "talos-public-ip-1"
  - "talos-public-ip-2"
  - "talos-public-ip-3"
traefikhttpport: 32080
traefikhttpsport: 32443



